<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X10_tab-2676-closeEl</name>
   <tag></tag>
   <elementGuidId>f5056d6a-a0b2-4619-bdd7-5823002757ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tab-2676-closeEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-2676-closeEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd4a6f32-a11e-47f5-8f6a-74b7c139e961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-2676-closeEl</value>
      <webElementGuid>cadb44ff-a8ac-4244-807d-6090e05d807f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tab-close-btn x-tab-close-btn-over u4-focused-element-frame</value>
      <webElementGuid>572a3cd3-0058-4014-a297-1217ea3a5643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e39a229-f6a4-4ca6-a3f3-a4457170740f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b244c93-a263-483a-8447-b9b669697619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close activity Supplier list (Alt+w)</value>
      <webElementGuid>f6bb9fb0-06e1-40dc-8eb4-0b8b4d112009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qtip</name>
      <type>Main</type>
      <value>Close activity (Alt+w)</value>
      <webElementGuid>b600ba5a-df1d-47ee-9258-2572579b568d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-2676-closeEl&quot;)</value>
      <webElementGuid>b34dd06a-b5fe-43fa-9b12-89119ebb9d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tab-2676-closeEl']</value>
      <webElementGuid>ef5222fe-586a-4275-9035-fe54324c32be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='tab-2676']/span[2]</value>
      <webElementGuid>4b0dbd08-493b-41e1-8357-5a01cd367dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span[2]</value>
      <webElementGuid>33e9c405-7a81-4fbf-bda3-98c8f798290d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tab-2676-closeEl']</value>
      <webElementGuid>8ed059ee-cc21-48b2-bfa5-a037875890f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
