<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Nav</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>82cab661-8dac-4b7f-b0a7-b7dfc62d62c7</testSuiteGuid>
   <testCaseLink>
      <guid>3d594bc5-3baa-4795-958f-4c8e35bf7623</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Navigation/Requisition Advanced</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6c489dff-f75f-483a-9ea2-d7ab24e58341</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Navigation/Suppliers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4187aa06-51c6-4ccc-ae89-7e8b88aaa3c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d76c4e-b614-4ea4-b3d6-ca6730db63d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fe5bdf0-ba14-4a5b-8523-ea3e61369148</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>492f6776-69c3-4486-a770-8538a15bd420</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
