<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accounting</name>
   <tag></tag>
   <elementGuidId>03c26e5f-b8ec-491a-bf4c-55e35f82cd17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u4_twolinestab-1607-multilineWrap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u4_twolinestab-1607-multilineWrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>052ec660-cfe1-499d-beb2-6a803867482d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u4_twolinestab-1607-multilineWrap</value>
      <webElementGuid>14e2082a-2861-4834-87a3-5a6baaa86ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u4-multilinebutton-mixin-line-wrapper</value>
      <webElementGuid>56445c72-06cd-438d-a20d-9f6061251bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accounting</value>
      <webElementGuid>0224e32f-5767-44f9-85dd-99f8581df475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u4_twolinestab-1607-multilineWrap&quot;)</value>
      <webElementGuid>eaece5df-adf2-415e-9980-4f793d7b673f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u4_twolinestab-1607-multilineWrap']</value>
      <webElementGuid>ba7c6b78-c6e4-4dd2-b99c-667eb183f2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='u4_twolinestab-1607']/div</value>
      <webElementGuid>008c0368-350b-4cde-b9e9-ab19acd3ca80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planner'])[1]/following::div[1]</value>
      <webElementGuid>487ea061-3a41-43ce-b4f4-e0a3c89f4a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customers and sales'])[1]/following::div[5]</value>
      <webElementGuid>600de48a-a7bf-444f-abef-932d1ee39be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Common'])[1]/preceding::div[4]</value>
      <webElementGuid>bcb675ab-7fdb-48cb-9dcd-aade1be9aff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[10]/div</value>
      <webElementGuid>5bbc3c99-4bf1-4abb-aea1-8b9102619b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u4_twolinestab-1607-multilineWrap' and (text() = 'Accounting' or . = 'Accounting')]</value>
      <webElementGuid>664687a4-b425-46c5-be29-3809aedd5140</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
