<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Supplier listWindow ID TRA015Accounting_af26b3</name>
   <tag></tag>
   <elementGuidId>f54dd9ac-88c6-450d-b14f-ae6c6139e888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ext-gen20993']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-gen20993</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ddd3b01d-b19f-4fbb-b1a9-a9ba340290ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u4-menu-search-result</value>
      <webElementGuid>5a84fec7-2e4a-453a-83c6-6c8fe17e86ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-potential-qtip</name>
      <type>Main</type>
      <value>Supplier list</value>
      <webElementGuid>a4399b0b-c535-43d1-b29b-6af3559e1cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen20993</value>
      <webElementGuid>93cd4786-0eae-41b3-8d57-ad4070e46ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supplier listWindow ID: TRA015Accounting/Accounts Payable/Vendor information</value>
      <webElementGuid>af53a632-52f7-4ea7-b450-ca073c8aac5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen20993&quot;)</value>
      <webElementGuid>0e1fc2da-65aa-4d65-a58b-14362fcfd058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ext-gen20993']</value>
      <webElementGuid>a79d0db1-ced5-4a41-a75f-108bffa55612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='u4_searchresultitem-2654']/div</value>
      <webElementGuid>4ab781cd-6dc2-4921-93cf-07c0342624be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit4 ERP'])[1]/following::div[14]</value>
      <webElementGuid>97190187-25d9-47d1-9998-d8d3c91cc44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Window options'])[1]/following::div[48]</value>
      <webElementGuid>b5f0c1b7-8403-4cb7-b4f2-22d86e3fe36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='list']/parent::*</value>
      <webElementGuid>cead0594-8f49-4160-b334-557d0eef51a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li/div</value>
      <webElementGuid>6daa0221-9a27-4a00-983b-0120d28ed468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ext-gen20993' and (text() = 'Supplier listWindow ID: TRA015Accounting/Accounts Payable/Vendor information' or . = 'Supplier listWindow ID: TRA015Accounting/Accounts Payable/Vendor information')]</value>
      <webElementGuid>dfff2462-ed6c-4907-9dfa-9e38426ade60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
