<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vendors</name>
   <tag></tag>
   <elementGuidId>a48e03d9-7c7d-4270-b7ed-4794369f1780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-gen34089</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[1]/div[2]/div[1]/div[2]/div[3]/div[2]/div/div/div/div/div/div[4]/div/div/div[2]/ul/li[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c794fb76-e562-4625-a032-8bf3b073e05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u4-menu-item-text</value>
      <webElementGuid>800a1fe2-1ff3-40ab-9ccf-9ee56be58396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen34089</value>
      <webElementGuid>656f80bf-c742-4e1b-935c-6d6bf8cc8e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-viewid</name>
      <type>Main</type>
      <value>TSU002</value>
      <webElementGuid>502bde94-5162-4db1-a925-5b37471bce76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Vendors</value>
      <webElementGuid>c228f529-a92a-4712-bf82-a45a2fc9a0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vendors</value>
      <webElementGuid>b8d784a0-92f7-42b6-b1c3-d63c2432a4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen34089&quot;)</value>
      <webElementGuid>ff93d160-0539-4039-bec3-9796e968d083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ext-gen34089']</value>
      <webElementGuid>2a844f79-7425-45d6-b0c6-80d1d52e9909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ext-gen34086']/div[3]</value>
      <webElementGuid>3aff6ce0-b4f0-4426-b68d-098ccc2a54e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor portfolio'])[2]/following::div[4]</value>
      <webElementGuid>45727f90-d5f5-4276-ba3d-22da808e5c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor information'])[2]/following::div[8]</value>
      <webElementGuid>a990abab-c8b4-4342-90f7-3569eb118173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor group'])[2]/preceding::div[3]</value>
      <webElementGuid>e96c463b-c041-4cd7-ac5a-33fc530571ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statement of accounts'])[3]/preceding::div[7]</value>
      <webElementGuid>acbea628-4350-4c94-a94e-e2a38ee1914f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[3]/div/div/div[2]/ul/li[2]/div/div[3]</value>
      <webElementGuid>9e0a0574-7ffc-4419-a39f-74dcfa7005de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ext-gen34089' and (text() = 'Vendors' or . = 'Vendors')]</value>
      <webElementGuid>675077e0-23af-40e4-9e68-56dd5578dfe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
