<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UNIT4_u4_textfield-1041-inputEl</name>
   <tag></tag>
   <elementGuidId>3ca4d5e1-7aa7-4179-9c10-53ee9bd6aa59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u4_textfield-1041-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u4_textfield-1041-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b31b18d6-4aa4-46d7-9640-3808757c9db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u4_textfield-1041-inputEl</value>
      <webElementGuid>1a17563a-e043-4da3-a6f0-19ec170686e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89cef3a4-35b4-4ef3-997f-35655deb540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>90b707ee-6f34-4c9d-b74e-5adbd28e93ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>u4_textfield-1041-inputEl</value>
      <webElementGuid>6afbb2c8-7bda-4d20-a5d0-321a31899be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search (Alt+q)</value>
      <webElementGuid>6f96b500-604e-415c-b77f-7f6956d916de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u4-search-input-field x-form-text u4-form-field-input x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>cbba7cd1-4e80-40e6-a7fc-9f686cf0e608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f9e7f4b3-a2ca-4875-85a9-c0bb046ac6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9090dc08-0183-4e47-a386-2ca2de27c0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search (Alt+q)</value>
      <webElementGuid>f03fb9f9-077e-4b3c-98d4-8c4061d87e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>04722f25-3a49-464d-af7a-a50c6057a1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a2c89da-f87b-4052-bf01-63af497250ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u4_textfield-1041-inputEl&quot;)</value>
      <webElementGuid>bef89390-b1fb-4d33-869b-10f356df6c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u4_textfield-1041-inputEl']</value>
      <webElementGuid>865ecb44-0090-44fd-aa2f-ccbe88a74c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='u4_textfield-1041-bodyEl']/input</value>
      <webElementGuid>2d9804a3-8287-4f32-9b90-95bb3b652eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8d092d15-2987-4dfe-92d8-c9aa26797286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'u4_textfield-1041-inputEl' and @type = 'text' and @name = 'u4_textfield-1041-inputEl' and @placeholder = 'Search (Alt+q)']</value>
      <webElementGuid>375855cd-ef7b-485d-87f2-5bf3a9fb0ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
