<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WarningIBA</name>
   <tag></tag>
   <elementGuidId>175e24c5-4380-4c02-8539-abe99e665ada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[2]/div/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u4_messageoverlay_warning-1499-innerCt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>668b7f68-96eb-4598-a1e8-c6c6bca8c731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u4_messageoverlay_warning-1499-innerCt</value>
      <webElementGuid>d4b9d84e-7859-477d-8c8e-43b3c6d89af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner </value>
      <webElementGuid>641419bc-1e89-496d-afa4-462aedfb0214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bcee729f-ce6e-4047-b227-727506aac69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WarningIBAN and Bank account are empty. One of these is usually required for electronic payment transfers.Successfully saved. Vendor ID 10016 is now created and is sent for approval.OK</value>
      <webElementGuid>1d64249a-5697-461a-9a4e-af65afed4c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u4_messageoverlay_warning-1499-innerCt&quot;)</value>
      <webElementGuid>f8ed2561-8473-470f-a5d3-9342b8339774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u4_messageoverlay_warning-1499-innerCt']</value>
      <webElementGuid>701ac9f4-3582-4dd4-a939-7d43dddb43b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u4_messageoverlay_warning-1499']/div[2]</value>
      <webElementGuid>4631d255-cc78-4f4e-b9ff-fa0e9bbf8bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendors'])[3]/following::div[31]</value>
      <webElementGuid>b79d4034-ea6c-4afb-9d14-b760e69629d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::div[42]</value>
      <webElementGuid>d3429237-801b-4ecf-b42a-e7194c16c67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]</value>
      <webElementGuid>aac590db-7d0e-49b5-9ced-6bae673f4329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u4_messageoverlay_warning-1499-innerCt' and (text() = 'WarningIBAN and Bank account are empty. One of these is usually required for electronic payment transfers.Successfully saved. Vendor ID 10016 is now created and is sent for approval.OK' or . = 'WarningIBAN and Bank account are empty. One of these is usually required for electronic payment transfers.Successfully saved. Vendor ID 10016 is now created and is sent for approval.OK')]</value>
      <webElementGuid>e641b80e-cafb-4d11-af63-84377e4837f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
