<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK_u4_pagebutton-1502-btnIconEl</name>
   <tag></tag>
   <elementGuidId>43705098-1f21-4777-a135-f51fbc70c0de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u4_pagebutton-1502-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='u4_pagebutton-1502-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb326ca2-e9bd-4a21-942a-f959a3530073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e889edc2-8ce2-4830-a96f-aa86213ee98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u4_pagebutton-1502-btnIconEl</value>
      <webElementGuid>1bccaf2b-2f2f-47a1-ae09-263bbd5d29a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>fadf1ba9-12f7-40c4-b56f-e658e4f47791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>530415b9-de1e-41c7-8d3d-a1fef9cacfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u4_pagebutton-1502-btnIconEl&quot;)</value>
      <webElementGuid>995cfa4f-998b-4b5e-9c95-b5653cb11342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='u4_pagebutton-1502-btnIconEl']</value>
      <webElementGuid>0fd92b90-58a2-4a9a-9945-cb55a05473a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u4_pagebutton-1502-btnEl']/span[2]</value>
      <webElementGuid>e34f96ed-603f-4cd5-a795-df378fb366e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/a/span/span/span[2]</value>
      <webElementGuid>4e460812-e104-4d6f-a6a3-1bf9b8cdcd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'u4_pagebutton-1502-btnIconEl']</value>
      <webElementGuid>be0db990-16a5-44b2-96dc-82711f092ee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
