<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contact_Info_tab_Add_button</name>
   <tag></tag>
   <elementGuidId>ede4ce38-5d3d-48fc-9e0d-6f4a211a2eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table/tbody/tr/td/div[1]/table/tbody/tr/td/div[2]/div[7]/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div[1]/div/div/div/div/div/table/tbody/tr/td/table/tbody/tr/td[1]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
