<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vendors_u4-messageoverlay-warning-icon</name>
   <tag></tag>
   <elementGuidId>80546a19-e8c3-402b-8164-272be5c1664b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.u4-messageoverlay-warning-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[2]/div/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2f3f7e0-835f-4202-992d-da4cf14e483d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u4-messageoverlay-warning-icon</value>
      <webElementGuid>44a6f2a5-3aad-436d-907f-c169c619e7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u4_container-1500&quot;)/div[@class=&quot;u4-messageoverlay-warning-icon&quot;]</value>
      <webElementGuid>4ef7990f-677c-4824-90fc-235cc9796846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u4_container-1500']/div</value>
      <webElementGuid>cdef1dff-a547-422f-8412-3f81d6e98271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div</value>
      <webElementGuid>ce1fc0fa-36f0-450d-89b1-61474b09d271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
