<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>External_Ref</name>
   <tag></tag>
   <elementGuidId>8d17a0b9-5f83-43d7-a6a8-6a0992181ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table/tbody/tr/td/div[1]/table/tbody/tr/td/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
