<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Short_name</name>
   <tag></tag>
   <elementGuidId>492d5cee-d0c1-415f-8eed-485bac3a52e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table/tbody/tr/td/div[1]/table/tbody/tr/td/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/table/tbody/tr[3]/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
