<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Update_rel_OK_Button</name>
   <tag></tag>
   <elementGuidId>106e08b7-2593-492c-8ca7-867ee7f7f180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table/tbody/tr/td/div[1]/table/tbody/tr/td/div[3]/table/tbody/tr[2]/td/div/div/table/tbody/tr/td[1]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
