<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vender_group</name>
   <tag></tag>
   <elementGuidId>1860d58a-2a00-41b1-a66e-ee628998ece8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table/tbody/tr/td/div[1]/table/tbody/tr/td/div[2]/div[2]/div/div[1]/div/div[2]/div[2]/table/tbody/tr[1]/td/table/tbody/tr[1]/td[1]/datalistcontrol/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
