<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vender_name</name>
   <tag></tag>
   <elementGuidId>8903eff9-84f1-4730-a9d4-eccdba41b4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/table/tbody/tr/td/div[1]/table/tbody/tr/td/div[2]/div[2]/div/div/div/div[2]/div[2]/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
